### ISSUE TITLE
Market.sell_limit() returns APISIGN_NOT_PROVIDED exception

### ISSUE THREAD

**Issue by sinaaghli** [gurpinars/bittrex-cpp#5]
Hi,
Thanks for sharing your great wrapper, I have been playing with this library which has been successful in reading market information but I'm getting an error if I try calling sell/buy methods. here is my example code
```
#include <iostream>
#include <bittrex-cpp/client.h>

int main(){
    std::string key="******";
    std::string secret="******";
    bittrex::Client cl(key,secret);
    bittrex::api::Market m = cl.get_market();
    auto ret = m.sell_limit("USDT-ADA",1.0,0.5);
    std::cout << "Done!" << std::endl;
}
```
and here is the error I get
```$ ./traderbot
terminate called after throwing an instance of 'fail'
  what():  APISIGN_NOT_PROVIDED
Aborted (core dumped)
```
I would appreciate any feedback.

**Comment by gurpinars** [comment]
Hi,
Thank you for your feedback.
The problem is that **struct curl_slist** had been freed before calling perform. I fixed the bug.You should be using account/market api without problem.
